stock_list:
  [ "etsy", "smr", "asts", "qubt", "rklb", "upst", "oklo",
    "rddt", "alab", "rgti", "rblx", "iren", "mp", "rcat", "qbts",
    "clsk", "nne", "vktx", "enph", "crcl", "sndk", "nbis", "crwv", "baba"]


# how much time take between the calls to the next time
time_to_sleep:
  600 # 10 minutes - 60 sec * 10

# how many candles get from IBKR app
candles_to_get:
  "4800 S" # 60 S - 1 minutes

# percentage_in_pattern - if is double top so the second top is under or the same price, or in bottom is above or the same price
difference_small_in_pattern:
  0.02

# percentage_in_pattern - if is double top so the second top is under or the same price, or in bottom is above or the same price
difference_large_in_pattern:
  0.1

# percentage_against - if is double top so the second top is above the first one, or in bottom is under the first one.
difference_small_against:
  0.02

difference_large_against:
  0.1

large:
  100

max_time_for_double:
  60 # 60 minutes